name: Bump Version

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed

jobs:
  bump:
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch on dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: |
          npm version patch -m "chore(release): bump patch version to %s [skip ci]"
          git push origin HEAD:dev --tags

      - name: Bump minor on main PR merge
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          npm version minor -m "chore(release): bump minor version to %s [skip ci]"
          git push origin HEAD:main --tags

      - name: Sync main to dev (auto-resolve conflicts)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          git fetch origin
          git checkout dev || git checkout -b dev
          git merge origin/main --ff -X theirs
          git push origin dev
