name: Bump Version

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  bump:
    if: github.ref == 'refs/heads/dev' || (github.event.pull_request.merged == true && github.base_ref == 'main')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm

      - name: Install deps
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch on dev
        if: github.ref == 'refs/heads/dev'
        run: |
          npm version patch -m "chore(release): bump patch version to %s [skip ci]"
          git push origin HEAD:dev --tags

      - name: Bump minor on main PR merge
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        run: |
          npm version minor -m "chore(release): bump minor version to %s [skip ci]"
          git push origin HEAD:main --tags
